apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: git-host-access-token
  namespace: cicd
spec:
  encryptedData:
    token: AgAhNGFq4EWIX2f1ZOjRzPPVuMPYcJvesy64odsZ4agdcy/KQwoFgtT65ayjMnSIyxqxt2y18VOWlae4AdhEkYUIcesWSGnuJIA7t+3MG8O3aMv0MCHQo+EZl9/OO0Nom4bSy0LxD+Dyo8zq6VG193xsiB5EjU6BjnwKpbutCSSvuHLhV/8scEfLbs9qozK/pMOndQgaVQZpvDD/38Hvr6ivgpxcXn/KrsNMaNZuat4hlZztOv9XGZsVlPBhqW3FC4LuTTwTymSZ5lnU6OP9ODooNdfVHfUqoPGKd7v3Wed+x2eeTlfHSr49RUcvn5FMjxLeC+aqlsaZ1DfKetfyV6w25Bh4oh/+6FFmYeriRkM1ASO6BMHnii0UfXz8ABevgO7PrxRyyr5WtPxiqeAKD2/BmksFDWYrybG8kvm2H5ryxQyRJQltFdKV+IKLsHErLFOMqgkUaFSUxklQQ4IYNrAem6cYKl6StnpMKbjp+g0J+4dHTM5PeY07H2ABVGFfS1GEbL4bigh4sr/UpYjUe7IZrvgLXS8ZbudpRzTEBonV1Qony9FS1f3KzuUjz66jXQoEblHYIbysOKyfUQQUI4Y37uWJs/+Bt/AgFsrDczmxmxTNf6ivwWVpSIzAOUVOxbvPx69ZxbiZhyOWoU+cSFTMPl83QpRQhyKyFybu6YGCTZhh6BfzgWVkbn4v9521XmoNl6GngQSQcrCINaoIF4L/sT3OQ7jj++jephhKH4KALUqYQ1azwIXs
  template:
    metadata:
      creationTimestamp: null
      name: git-host-access-token
      namespace: cicd
    type: Opaque
