apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitops-webhook-secret
  namespace: cicd
spec:
  encryptedData:
    webhook-secret-key: AgAUVmh2dorggTvvSveP8Jnp38J/K8w68a30qXvPzz0ljXFVoPnFMl58cJCp1h6LtM+dz9eHgKVGZTDWhH8hkbkfBtycNCBpaTiFS18cqn3YasditWiu8moBVoimcITmIDvmn/Uk+CniIP/c4qq2bNyhXk6SKEiw8DnJAqFuiFe0AuafXVldBRE0eGoM7uzAq8wAipVl4Jyj7XACvIC02LKqS5JlRsiaQpoJfS3Wdlnl4JmOKuAIRNPx5Qqy/3t3Wyh49AExla1dw47UqV3uFnZF3EDI4Z/sGkLotJvVYNqPj0tV3IBOujd7etbA1cq7k8u13JyfayCEzSwlMVenKFGPzQrJgfbDUT8ihWk4fWlQsNghFUyir6lBp4LhswKV0aSlUwvqy0NS2Qz/kMQupjOl5QBJ/AU0MB08wKPikg0U2h9/KvF/WfVICIIVtLepOkYLSXajfXb5/gqbfVONXN/FFboEMn1vNYp3YnILqCJhWOJ1bP2Ydow9FauzZc2CxXBfyuiAsrhfvPtWC5mjNtdPhi4rB/EcAltP8RL0Fp1uB+/uTmp5C6ay7U0Nqq0U+yCNq+NlmbZuWCrMnf4Zck4B3nkkjbbSDLerioZJv74phJ2V9bABqmuoHX/sFDIm9B2IivLs5R2ISlNci/ozUuO3/2qBkCCdeoIx1KKaGPXWPiZhu4LEHDzR9ikhPnbcgQ8mMjskP7G7/PBE5Qx/AplJlOBMQQ==
  template:
    metadata:
      creationTimestamp: null
      name: gitops-webhook-secret
      namespace: cicd
    type: Opaque
