apiVersion: bitnami.com/v1alpha1
kind: SealedSecretController
metadata: 
  name: sealedsecretcontroller
  namespace: cicd
spec: 
  affinity: {}
  nodeSelector: {}
  securityContext: 
    fsGroup: ""
    runAsUser: ""
  serviceAccount: 
    name: ""
  tolerations: []